[package]
authors = ["realityone <realityone@me.com>"]
name = "rsping"
version = "0.1.0"

[dependencies]
clap = "2.26.2"
error-chain = "0.11.0"
ipnetwork = "0.12.7"
lazy_static = "0.2.9"
pnet = "0.19.0"
